---
- name: deploy and service
  hosts: master
  gather_facts: no
  become: yes

  tasks:
    - name: git clone or pull
      git:
        repo: http://github.com/oncliff/cicdtest.git
        dest: /root/0220
        clone: yes
        update: yes
        force: yes

    - name: kubectl apply
      shell: kubectl apply -f /root/0220/jenkins.yaml
